version: "3.7"
services:

  policy-api1:
    build:
      context: .
      dockerfile: Dockerfile
    image: orchestracities/anubis-management-api:test
    networks:
      - envoymesh
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost
      - CORS_ALLOWED_METHODS=*
      - CORS_ALLOWED_HEADERS=*
      - DEFAULT_POLICIES_CONFIG_FILE=/home/apiuser/config/opa-service/default_policies.ttl
      - DEFAULT_WAC_CONFIG_FILE=/home/apiuser/config/opa-service/default_wac_config.yml
      - DB_TYPE=postgres
      - DB_HOST=postgresserver1
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=anubis
      - KEYCLOACK_ENABLED=True
      - TENANT_ADMIN_ROLE_ID=9dc79aa8-d42f-4720-8de0-fe79a00a46b7
      - KEYCLOACK_ADMIN_ENDPOINT=http://keycloak:8080/admin/realms/default
    ports:
      - "8085:8000"
    volumes:
      - ./config/opa-service/default_policies.ttl:/home/apiuser/config/opa-service/default_policies.ttl
      - ./config/opa-service/default_wac_config.yml:/home/apiuser/config/opa-service/default_wac_config.yml
    depends_on:
      - postgresserver1

  policy-api2:
    build:
      context: .
      dockerfile: Dockerfile
    image: orchestracities/anubis-management-api:test
    networks:
      - envoymesh
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost
      - CORS_ALLOWED_METHODS=*
      - CORS_ALLOWED_HEADERS=*
      - DEFAULT_POLICIES_CONFIG_FILE=/home/apiuser/config/opa-service/default_policies.ttl
      - DEFAULT_WAC_CONFIG_FILE=/home/apiuser/config/opa-service/default_wac_config.yml
      - DB_TYPE=postgres
      - DB_HOST=postgresserver2
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=anubis
      - KEYCLOACK_ENABLED=True
      - TENANT_ADMIN_ROLE_ID=9dc79aa8-d42f-4720-8de0-fe79a00a46b7
      - KEYCLOACK_ADMIN_ENDPOINT=http://keycloak:8080/admin/realms/default
    ports:
      - "8086:8000"
    volumes:
      - ./config/opa-service/default_policies.ttl:/home/apiuser/config/opa-service/default_policies.ttl
      - ./config/opa-service/default_wac_config.yml:/home/apiuser/config/opa-service/default_wac_config.yml
    depends_on:
      - postgresserver2

  postgresserver1:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anubis
    networks:
      - envoymesh

  postgresserver2:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anubis
    networks:
      - envoymesh

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-19.0.1}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/oc-custom.jar:/opt/keycloak/providers/oc-custom.jar
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
    command: start-dev --import-realm
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh:
