sequenceDiagram
    participant pap1
    participant p2p1
    participant p2p2
    participant pap2
    pap1->>p2p1: create policy
    p2p1->>p2p1: (if topic does not exist) create topic
    p2p1->>p2p1: (if topic does not exist) register as a content provider for the topic
    p2p1->>p2p1: (if not subscribed to the topic) subscribe to the topic
    p2p1->>p2p1: `create policy` message published on the topic
    p2p1->>p2p2: notify nodes subscribed to the topic
    p2p2->>pap2: register policy