# TODO: This will eventually be a different more fitting wac format
"acl:Authorization":
  - "acl:accessTo":
      value: "default"
      type: "*"
    "acl:agentClass":
      - "acl:AuthenticatedAgent"
    "acl:mode":
      - "acl:Read"
  - "acl:accessTo":
      value: "default"
      type: "*"
    "acl:agentClass":
      - "acl:agentClass:Admin"
    "acl:mode":
      - "acl:Control"
