plugins:
  envoy_ext_authz_grpc:
    addr: ":9191"
    path: envoy/authz/allow
    dry-run: false
    enable-reflection: true
decision_logs:
  service: acmecorp
  resource: v1/audit/logs
  reporting:
    min_delay_seconds: 30
    max_delay_seconds: 60
services:
  acmecorp:
    url: http://policy-api:8000
#    url: https://eoweg4wf20s8kud.m.pipedream.net
    response_header_timeout_seconds: 5
