name: Update OpenAPI spec

on: [push]

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Start anubis
        working-directory: .
        run: |
          docker build -t orchestracities/anubis:latest .
          docker run -p 127.0.0.1:8085:8000/tcp --name anubis -d orchestracities/anubis:latest
      - name: Update Open API spec
        working-directory: ./scripts
        run: |
          ./download_open_api.sh
      - name: Generate walktrhough
        working-directory: .
        run: |
          npm install -g openapi-markdown
          openapi-markdown -i open-api-spec/openapi.json -o docs/user/walkthrough.md
          sed -i '1s/^/<!-- markdownlint-disable -->/' docs/user/walkthrough.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update open api specs
      - name: Clean up
        run: |
          docker rm -f anubis
