name: Update OpenAPI spec

on: [push]

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup demo
        working-directory: ./scripts
        run: |
          ./run_demo.sh
      - name: Update Open API spec
        working-directory: ./scripts
        run: |
          ./download_open_api.sh
      - name: Generate walktrhough
        working-directory: .
        run: |
          npm install -g widdershins
          widdershins open-api-spec/openapi.json -o docs/user/walkthrough.md --omitHeader
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update open api specs
      - name: Clean up
        working-directory: ./scripts
        run: |
          ./clean.sh
