name: Update OpenAPI spec

on: [push]

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: orchestracities/anubis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Start anubis
        working-directory: ./scripts
        run: |
          docker run -p 127.0.0.1:8085:8000/tcp --name anubis -d orchestracities/anubis:latest
      - name: Update Open API spec
        working-directory: ./scripts
        run: |
          ./download_open_api.sh
      - name: Generate walktrhough
        working-directory: .
        run: |
          npm install -g openapi-markdown
          openapi-markdown -i open-api-spec/openapi.json -o docs/user/walkthrough.md
          sed -i '1s/^/<!-- markdownlint-disable -->/' docs/user/walkthrough.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update open api specs
      - name: Clean up
        run: |
          docker rm -f anubis
