name: Policy API Tests

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
          cache-dependency-path: |
            anubis-management-api/Pipfile.lock
      - name: Install pipenv
        working-directory: ./anubis-management-api
        run: pip install pipenv
      - name: Run python tests
        working-directory: ./anubis-management-api
        run: |
          pipenv install --dev
          pipenv run pytest
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-api
          platforms: linux/amd64,linux/arm64
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Setup demo
        working-directory: ./scripts
        run: |
          ./run_demo.sh
      - name: Test CORS
        working-directory: ./scripts
        run: |
          ./test_cors.sh
      - name: Test demo
        working-directory: ./scripts
        run: |
          ./test_context_broker.sh
      - name: Clean up
        working-directory: ./scripts
        run: |
          ./clean.sh
  # opa:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Test Rego
  #       working-directory: ./scripts
  #       run: |
  #         curl -L -o opa https://openpolicyagent.org/downloads/v0.37.2/opa_linux_amd64_static
  #         chmod 755 ./opa
  #         ./test_rego.sh
