name: Policy API Tests

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
          cache-dependency-path: |
            auth-management-api/Pipfile.lock
      - name: Install pipenv
        working-directory: ./auth-management-api
        run: pip install pipenv
      - name: Run python tests
        working-directory: ./auth-management-api
        run: |
          pipenv install --dev
          pipenv run pytest
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Setup demo
        working-directory: ./scripts
        run: |
          ./run_demo.sh
      - name: Test demo
        working-directory: ./scripts
        run: |
          ./test_context_broker.sh
  opa:
    runs-on: ubuntu-latest
    steps:
      - name: Intall opa
        working-directory: ./scripts
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.37.2/opa_linux_amd64_static
          chmod 755 ./opa
      - name: Test Rego
        working-directory: ./scripts
        run: |
          ./test_rego.sh