name: Policy API Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
          cache-dependency-path: |
            auth-management-api/Pipfile.lock
      - name: Install pipenv
        working-directory: ./auth-management-api
        run: pip install pipenv
      - name: Run tests
        working-directory: ./auth-management-api
        run: |
          pipenv install --dev
          pipenv run pytest
