name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        working-directory: ./auth-management-api
        run: pip install pipenv
      - name: Run tests
        working-directory: ./auth-management-api
        run: |
          pipenv install --dev
          pipenv run pytest
